### ISSUE TITLE
LBCD connection issues 

### ISSUE THREAD

**Issue by kodxana** [lbryio/dashboard#2]
```madiator2011@madtalk:/media/Linuxx/dashboard/lbcd-monitor$ Traceback (most recent call last):
  File "monitor.py", line 124, in <module>
    main()
  File "monitor.py", line 82, in main
    info = lbcd('getinfo')
  File "monitor.py", line 48, in lbcd
    return json.loads(output.decode('utf-8'))
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)```

**Comment by kodxana** [comment]
Fixed by creating dummy lbcd.conf file with content od lbcd docker :)
